### ISSUE TITLE
Gray page

### ISSUE THREAD

**Issue by errecielle** [seblucas/cops#499]
I have Cops installed on my web server but the only thing I see is a gray page. My server log reports these errors which, you will excuse me, I am absolutely unable to decipher.
The metadata.db file is from Calibre 5.9. The PHP version is 7.4

17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: PHP Fatal error: Uncaught Error: Call to a member function fetchColumn() on bool in /web/htdocs/www.cardosolaynes.com/home/cops/base.php:1295: /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
-- | --
17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: Stack trace:: /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #0 /web/htdocs/www.cardosolaynes.com/home/cops/base.php(1302): Base::executeQuerySingle(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #1 /web/htdocs/www.cardosolaynes.com/home/cops/author.php(43): Base::getCountGeneric(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #2 /web/htdocs/www.cardosolaynes.com/home/cops/base.php(613): Author::getCount(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #3 /web/htdocs/www.cardosolaynes.com/home/cops/JSON_renderer.php(192): Page->InitializeContent(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #4 /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php(16): JSONRenderer::getJson(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #5 {main}: /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
17/01/2021 14:54:35 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: thrown in /web/htdocs/www.cardosolaynes.com/home/cops/base.php on line 1295: /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: PHP Fatal error: Uncaught Error: Call to a member function fetchColumn() on bool in /web/htdocs/www.cardosolaynes.com/home/cops/base.php:1295: /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: Stack trace:: /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #0 /web/htdocs/www.cardosolaynes.com/home/cops/base.php(1302): Base::executeQuerySingle(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #1 /web/htdocs/www.cardosolaynes.com/home/cops/author.php(43): Base::getCountGeneric(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #2 /web/htdocs/www.cardosolaynes.com/home/cops/base.php(613): Author::getCount(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #3 /web/htdocs/www.cardosolaynes.com/home/cops/JSON_renderer.php(192): Page->InitializeContent(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #4 /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php(16): JSONRenderer::getJson(): /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: #5 {main}: /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php
17/01/2021 14:54:30 | [error] [client 93.42.106.226] - www.cardosolaynes.com - AH01215: thrown in /web/htdocs/www.cardosolaynes.com/home/cops/base.php on line 1295: /web/htdocs/www.cardosolaynes.com/home/cops/getJSON.php, referer http://www.cardosolaynes.com/cops/index.php

Thank you for your help to solve this issue.

Regards

Roberto

**Comment by marioscube** [comment]
A grey screen is usually caused by an error in the settings in config_local.php

please post your config_local.php

NB: edit out your domain name and external IP from your post above.
You do not want the whole world be able to access you webserver!

**Comment by errecielle** [comment]
First of all thank you...
here the config_local.php

<?php
    if (!isset($config))
        $config = array();
  
    /*
     * The directory containing calibre's metadata.db file, with sub-directories
     * containing all the formats.
     * BEWARE : it has to end with a /
     */
    $config['calibre_directory'] = '../files/libri/bibliotecadicalibre/';
    
    /*
     * Catalog's title
     */
    $config['cops_title_default'] = "RCL";
    
    /*
     * use URL rewriting for downloading of ebook in HTML catalog
     * See README for more information
     *  1 : enable
     *  0 : disable
     */
    $config['cops_use_url_rewriting'] = "1";

**Comment by marioscube** [comment]
Your config_local.php file should start with:

<?php                                                                                                                                                                         
                                                                                                                                                                                                   
    if (!isset($config)) {                                                                                                                                                                         
        $config = array();                                                                                                                                                                         
    }

maybe yours does or doesn’t.

**Comment by marioscube** [comment]
<?php

**Comment by errecielle** [comment]
[config_local.php.txt](https://github.com/seblucas/cops/files/5826576/config_local.php.txt)

**Comment by marioscube** [comment]
That looks correct.

you could try the absolute path to the calibre library

http://........../cops/checkconfig.php gives no error?

**Comment by errecielle** [comment]
![Immagine 2021-01-17 193525](https://user-images.githubusercontent.com/8911117/104852407-2ffbd180-58fb-11eb-899e-b12307b952b4.png)

All seems to be ok...

**Comment by marioscube** [comment]
Did you install a release zip or git pull?

use the zip.

php 7.4 should work.

Just for testing:
Either install the calibre library in ../cops ( and adjust config_local.php ;-) )

or 

chmod 777 your existing library to make sure permissions do not mess things up.
You can always change it back to what it was.

**Comment by errecielle** [comment]
I've installed the release zip: cops-1.1.3.zip
The library is very large so I've changed the permissions to the library directory and all the sub to 777
Also the metadata.db have 777 as permissions.

Thanx again for your time...

rcl

**Comment by marioscube** [comment]
10000 books should be no problem, even on a slow (not very old and slow) server.
Memory could be a problem. Cops starts with reading the metadata.db in memory (In my experience).

**Comment by errecielle** [comment]
The books are around 4500 so this should not be a problem

**Comment by marioscube** [comment]
Sometimes if something does not work a reinstall and new setup of config files fixes the problem.

the error with the base.php file suggest that something with a php file does not work as it should. What? I do not know.

**Comment by errecielle** [comment]
😂 😂 😂
Ok. Tomortow I'll reinstall and keep you updated.

**Comment by errecielle** [comment]
Nope :-(
I've reinstall from scratch, I've tried to move the calibre directory under /cops but nothing happens and the log errors are the same...

**Comment by marioscube** [comment]
What OS (Linux debian, ubuntu, centos, etc) do you use? And what webserver (if Apache I can try to help)?

Maybe I can recreate and test your setup in a VM.

**Comment by errecielle** [comment]
I'm using a server provided by a server farm here in Italy. Aruba. So I'm
not able to answer this type of questions.
It's an hosted solution.

I'll check with the provider.

Thank you again.

Roberto

Il giorno lun 18 gen 2021 alle ore 11:37 marioscube <
notifications@github.com> ha scritto:

**Comment by marioscube** [comment]
I did some testing (just for fun), but it did not solve your problem.

My findings are that it is NOT:
 - cops: it just works
 - CentOS: I tested with centOS 8 (your provider probably uses centOS 7, but I see no real problem there)
 - Apache: no problems
 - PHP: i tested with one version lower and one version higher than your setup, both no problem
 - Calibre version: I installed latest version and no problem there.

What could be the problem:
- calibre database: can you make a small (2 or 3 books and no custom things) database with calibre and test that.
- missing php extensions (should not be, because cops said it's ok).
Make small file in the cops directory and name it test.php
`<?php
phpinfo()
?>`
then, in your browser goto this file http://<>IP or URL>/cops/info.php
maybe post the output in a file here.
- error in the php_config.php file (but I saw no errors there).

**Comment by errecielle** [comment]
First of all thank you very much for your support
Secondly I've tried this:
- create a calibre database with 3 books. Same gray page
- create a test.php file and opened in the browser: attached you can find the zip file with all the page (hopefully I've blanked all the ip number :-) )
- I can confirm the checkconfig.php file shows no errors

In addition I've posted a question to the tech of the provider but I've little hope they answer this type of questions
 
[PHP 7.4.10 - phpinfo().zip](https://github.com/seblucas/cops/files/5850686/PHP.7.4.10.-.phpinfo.zip)

**Comment by marioscube** [comment]
Aaahhrrrggg I should have thought of this earlier (I must be getting old and forgetfull). It's this #48 problem all over again with.centOS 7!

The calibre database made with Calibre 5 does not work with the php-sqlite3 version included in centOS 7. I think, based on their website, that Aruba uses centOS 7 as OS.  

This thread in #487 gives a nice solution to your problem if you are comfortable with changing some of the COPS code.
If not, let me know.

**Comment by errecielle** [comment]
If it's a simple CTRl-C - Ctrl-V, yes I'm able to do that. 

 // --------------------------------------------------------------------------------
    // -- Fix for incompatibility older sqlite3 & Calibre v5 database format
    // true will create metadata.dbv4 and use that copy
    $config['sqlite_fix'] = true;
    $config['dumpfile'] = '/tmp/metadata.dump';
    $config['sqlite3pgm'] = '/opt/bin/sqlite3';
    // leave this false unless debugging is required with url /getJSON.php?complete=1
    $config['sqlite_fix_debug'] = false;  
    // --------------------------------------------------------------------------------

But... where?

**Comment by marioscube** [comment]
See: [https://github.com/jvanderzande/cops/commit/9abeffa462b3c72984931ac3e44300931f387767](url)

The above part in config_local.php

The larger part in ../cops/lib/base.php

I have not tried this last iteration of this solution.

**Comment by errecielle** [comment]
we, you, are close, I feel it :-)

Now the error is in the path for the db:
"
File ../files/libri/calibre/metadata.dbv4 not found, Please check
I've tried to modify the path in  $config['dumpfile'] =
'/tmp/metadata.dump'; because I don't have a tmp directory so I've put the
same of the db but it seems not working




Il giorno gio 21 gen 2021 alle ore 19:32 marioscube <
notifications@github.com> ha scritto:

**Comment by marioscube** [comment]
What worx for me:

1 - make e tmp directory in ../cops

2 - copy the config_local.php file in ../cops (or after evaluating my changes copy the changes to your config_local.php
[config_local.php.txt](https://github.com/seblucas/cops/files/5852607/config_local.php.txt)

3 - replace the existing ../cops/lib/Base.php (or rename first to Base.php.orig)with this Base.php 
[Base.php.txt](https://github.com/seblucas/cops/files/5852610/Base.php.txt)

4 - check if it works.

There is one problem with this fix. It only works if you use just one calibre library in COPS. I use multiple, so I do not use this fix.

**Comment by errecielle** [comment]
I checked your files with mine and I don't see any particular differences
but some must be there because now I have this error message:
-
Check if Calibre database file contains at least some of the needed tablesNot
all Calibre tables were found. Are you sure you're using the correct
database.
It actually created the .dbv4 file but created it empty.
I also tried to move the calbre folder under /cops but the error remains
the same.

I've checked the permissions and all 777
[image: Immagine 2021-01-22 075226.png]



Il giorno ven 22 gen 2021 alle ore 00:13 marioscube <
notifications@github.com> ha scritto:

**Comment by marioscube** [comment]
Is there a metadata.dump file in ../cops/tmp/ ?

**Comment by errecielle** [comment]
Yes. There is

[image: Immagine 2021-01-22 141748.png]

Il giorno ven 22 gen 2021 alle ore 08:24 marioscube <
notifications@github.com> ha scritto:

**Comment by marioscube** [comment]
The image does not work, but I believe you. Size of metadata.dump is > 0?

I will test again with my antique setup.

**Comment by errecielle** [comment]
Yes...

![Immagine 2021-01-22 141748](https://user-images.githubusercontent.com/8911117/105510515-0530c500-5ccf-11eb-85ca-04571c6aa68b.png)

**Comment by errecielle** [comment]
I don't know if this matters but the sizes of metadata.db and metadata.dump are different
The first one is 405.504.

**Comment by marioscube** [comment]
That is ok.
The size of metadata.dump seems a bit small though.....
 
You have tried to delete metadata.dump and metadata.dbv4 and then tried it again

**Comment by errecielle** [comment]
Yes, more or less five times switching the calibre folder up and down...
I'll retry again now

Il giorno ven 22 gen 2021 alle ore 16:42 marioscube <
notifications@github.com> ha scritto:

**Comment by errecielle** [comment]
same as before

![Immagine 2021-01-22 164538](https://user-images.githubusercontent.com/8911117/105512493-74a7b400-5cd1-11eb-8f90-5ef995abcc7f.png)
![Immagine 2021-01-22 164624](https://user-images.githubusercontent.com/8911117/105512495-75404a80-5cd1-11eb-9d93-11970be21b74.png)

**Comment by marioscube** [comment]
What are the "Permessi" of folder../files/libri/bibliotecadicalibre/. ?

**Comment by errecielle** [comment]
777 and the same for all the sub, the files 
Only metadata_db_prefs_backup.json have 755

**Comment by marioscube** [comment]
I'm searching my disks for a batch file I made that you could run, but I can't find it.........

I will try again this evening.

**Comment by marioscube** [comment]
I have no clue why it does not work for you, but here is plan B!

**_Plan B_**
1 - open a terminal on the server
2 - go to ../files/libri/bibliotecadicalibre
3 - type: nano convert.sh (or any other name you like)
4 - copy this into the nano editor

**#!/bin/bash
rm -f metadata.dbv4 
sqlite3 metadata.db .dump > metadata.dump
sqlite3 metadata.dbv4 < metadata.dump
rm -f metadata.dump
echo "done ....."**

save with <ctrl>x and yes
5 - make executable: chmod +x convert.sh
6 - run this executable: ./convert.sh
7 - there should be a metadata.dbv4 file in the calibre directory. Is there?
8 - got cops in a browser.
9 - report back

**Comment by errecielle** [comment]
Unfortunately I can't access neither terminal nor sqlite 😖 .
Is it possibile to run this batch as php?


Il giorno ven 22 gen 2021 alle ore 23:21 marioscube <
notifications@github.com> ha scritto:

**Comment by marioscube** [comment]
You cannot use ssh?
You only use ftp?

Maybe tomorrow or Monday I can hack something together that is php.

**Comment by errecielle** [comment]
Yep... Only ftp

Il giorno sab 23 gen 2021 alle ore 19:25 marioscube <
notifications@github.com> ha scritto:

**Comment by marioscube** [comment]
OK, plan C: ;-)

1 - clear of files ../cops/tmp
2 - copy metadata.db from your calibre directory to ../cops/tmp
3 - copy this php file to ../cops/tmp (without the .txt :-)
[convert-metadata.php.txt](https://github.com/seblucas/cops/files/5862574/convert-metadata.php.txt)
4 - in browser http://<IP or URL>/cops/tmp/convert-metadata.php
5 - you should see: Start .....   end!
6 - copy the metadata.dbv4 to your calibre library
7 - then cops in browser.
8 - did this help?

**Comment by errecielle** [comment]
Plan C probably show us which is the problem...
All the steps form 1 to 5 were ok but... the dbv4 is empty :-( 

![Immagine 2021-01-24 172951](https://user-images.githubusercontent.com/8911117/105636837-6e007480-5e6a-11eb-8cfd-baea40408913.png)

**Comment by errecielle** [comment]
If this should help I can send you the metadata.db to understand something else. 
Should the problem is the sqlite3 on my server?

**Comment by errecielle** [comment]
Could the problem be in sqlite 3 on my server?
If you think this should help in understanding the problem I can send you my metadata.db

**Comment by marioscube** [comment]
The problem is the splite3, or when making the metadata.dbv4 file your metadata.db file.

You could try sending it to me and see if I can convert it.

**Comment by errecielle** [comment]
Here or where?

Il giorno dom 24 gen 2021 alle ore 18:19 marioscube <
notifications@github.com> ha scritto:

**Comment by marioscube** [comment]
Mail to my username at gmail.com

**Comment by errecielle** [comment]
Done.

In parallel I've installed sqlite3 on my pc and, searching the web, I've
found some help on how to use it.

sqlite> .open metadata.db
sqlite> .output metadata.dbv4
sqlite> .dump
sqlite> .output stdout

Probably in the commands I'm missing something because the dbv4 file is not
working


Il giorno dom 24 gen 2021 alle ore 18:32 marioscube <
notifications@github.com> ha scritto:

**Comment by marioscube** [comment]
I have an empty in-box on marioscube at gmail.com?

to run sqlite3 and try for yourself:

1 - make dumpfile:
sqlite3 metadata.db .dump > metadata.dump

2 - read txt dump in database:
sqlite3 metadata.dbv4 < metadata.dump

**Comment by DB99** [comment]
I have a somewhat datted QNAP NAS TS-421 running the latest COPS version installed from source from Jos jvanderzande's fork which incorporate the fixes to lib/Base.php and config_local.php.  Ther process works flawlessly and createts a correct metadata.dbv4 file.  However, the grey page persists and checkconfig.php cannot verify the database.  A check of the v4 database shows the annotations tables still present.  Removing the new annotations tables results in proper functioning.  Is there any step in the process which is intended to delete these tables or should COPS be able to function with them in the dbv4 database?  Thanks in anticipation of assistance.

**Comment by DB99** [comment]
I've attached a zip file with my config_local.php, the debug log and the resulting metadata.dbv4 file.  The metadata.dbv4 contains the fts annotations tables and does not work.  However, removing these tables does result in it working with COPS.  It seems that on my \\ QNAP the dump is creating the dbv4 metadata with all of the fts annotations tables without actually fixing them.

I'd like to know why.  If not I might try modifying your code to simply copy the metadate.db to metadata.dbv4 rather than creating the latter via the dump command, then dropping the offending tables in the dbv4 file and using that for COPS.  As the dbv4 file is used only for COPS I don't see any real downside to this approach.  Thanks for your hard work on this.  I'd love to know what's causing the problem.

[configs.zip](https://github.com/seblucas/cops/files/7385029/configs.zip)

**Comment by jvanderzande** [comment]
I had to create a symlink to be able to access the library from the webserver.
This is what I documented in my config:
```
//// from command prompt: Create link in website directory for COBS to the Calibre directorie(s) to be able to view them
//~   cd /share/Web/calibre
//~   ln -s /share/Public/ebooks /share/Web/calibre/ebooks
// I have 2 directories hence the array:
$config['calibre_directory'] = array ("Nederlands" => "./ebooks/Calibrebibliotheek-NL-NAS/", "English" => "./ebooks/Calibrebibliotheek-EN-NAS/");

```

**Comment by DB99** [comment]
@jvanderzande 
 
Thanks a lot for your help.  My sqlite3 version is 3.21.0 2017.t
I'm sure that the cause of the problem is exactly as you describe. For the time being It works well by simply copying the database and deleting these tables.  At this stage  modified lib/Base.php to simply use the dbv4 metadata which I produce manually.
I tried the code from @inbux on the other thread which I incorporated into the lib/Base.php file in a second cops directory on the server. So far I haven't got it working.  It fails to copy the metadata.db to metadata.dbv4.  I need to check if it is a permissions problem or perhaps some syntax problem.  Unfortunately I'm not a php expert.

Once again thanks for your help.  if I get it working I will post the relevant code in this thread.

**Comment by randomwraith** [comment]
With regards to the blank grey page problem, are you using **nginx**?

I have just migrated from apache to nginx and this frustrating problem surfaced. It was only by chance that I noticed that an unrelated page required a long scroll to reach the content and wondered if it was a manifestation of the same problem. 

It turns out in my case the following server directive in my page configuration was interfering with the page load:

`add_header Content-Security-Policy "default-src 'self';";`

If you have this in your config, try commenting it out.  Doing so solved the problem for me and cops is working AOK again.

For what its worth, I'm using Debian 11 (bullseye) with PHP 7.4, nginx 1.18
