### ISSUE TITLE
Calibre "apsw.CantOpenError: CantOpenError: unable to open database file" ; deadlock with COPS installed on SYNOLOGY ?

### ISSUE THREAD

**Issue by Flyingdishes** [seblucas/cops#502]
Hi, 
Since a few weeks Calibre fails in adding new books on the epub repositoy (and database) installed on my SYNOLOGY NAS.

Contacting Calibre team, they push back, arguing that Calibre is not suoorted on NAS installations.

I wonder if this is an issue between Calibre and COPS file management.

Anybody facing that issue ?

Thanks for any educated feedback.

COPS version 1.1.3
calibre, version 5.17.0

LOG capture: 
ERREUR : Erreurs pendant l'ajout: Échec à l'ajout de n'importe quels livres, cliquez sur "Afficher les détails" pour plus d'information.

----------------------------------------------------------------------
Échec à ajouter le livreUn mal pour un bien
	D:/Telechargements/Danielle Steel - Un mal pour un bien 2019 2021.epub
Avec l'erreur :
Traceback (most recent call last):
  File "calibre\gui2\add.py", line 457, in add_book
  File "calibre\db\legacy.py", line 334, in create_book_entry
  File "calibre\db\cache.py", line 72, in call_func_with_lock
  File "calibre\db\cache.py", line 1686, in create_book_entry
  File "calibre\db\cache.py", line 1399, in set_metadata
  File "calibre\db\cache.py", line 1223, in update_path
  File "calibre\db\backend.py", line 1665, in update_path
  File "calibre\db\tables.py", line 134, in set_path
  File "calibre\db\backend.py", line 920, in execute
apsw.CantOpenError: CantOpenError: unable to open database file

**Comment by marioscube** [comment]
1 - COPS does not write to the calibre database and as far as I know does not lock it either. So probably not a COPS issue!

2 - If calibre cannot write to the (networked) directory/database there is probably a rights issue on your Synology.
Make sure you can write to the networked directory (try to copy a file with windows to the networked directory, and then delete it).

**Comment by Flyingdishes** [comment]
Hi Sebastien and Mario,

Thanks for the attention and answer. I posted my answer on https://github.com/seblucas/cops/issues/502#issuecomment-836628451

Indeed COPS had nothing to do with the issue . It was a change in Synology DSM security rules since last DSM update.

By the way, I am a big fan of COPS that I heavily use with my family and friends !
I imported on my Synology the last COPS update (version 1.1.3) which is not yet available on Synologycommunity which only provides Version 1.0.1-5. A simple copy/paste of 1.1.3 code made available by Sebastien was enough.
Any future version of COPS to expect ? 😉

Again thank you for this brilliant idea of making COPS available!

Flying


De : marioscube ***@***.***>
Envoyé : lundi 10 mai 2021 14:20
À : seblucas/cops ***@***.***>
Cc : Flying ***@***.***>; Author ***@***.***>
Objet : Re: [seblucas/cops] Calibre "apsw.CantOpenError: CantOpenError: unable to open database file" ; deadlock with COPS installed on SYNOLOGY ? (#502)


1 - COPS does not write to the calibre database and as far as I know does not lock it either. So probably not a COPS issue!

2 - If calibre cannot write to the (networked) directory/database there is probably a rights issue on your Synology.
Make sure you can write to the networked directory (try to copy a file with windows to the networked directory, and then delete it).
